# Generated by Django 2.1.3 on 2018-11-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181117_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('FN', 'fun'), ('RX', 'relax'), ('EX', 'experience'), ('SI', 'sights')], default='FN', max_length=20),
        ),
    ]
