# Generated by Django 2.1.3 on 2018-12-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20181124_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrun',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventrun',
            name='time',
            field=models.TimeField(),
        ),
    ]
